main: fr.jupidev.furnace.Main
name: Furnace
version: "1.6"
api-version: 1.8.8
author: Jupiter_56

commands:
  furnace:
    description: This is a command for cooking items.
  furnaces:
    description: This is a command for settings.
    permission: furnace.settings

