main: fr.jupidev.furnace.Main
name: Furnace
version: "1.5"
api-version: 1.8.8
author: JupiDev

commands:
  furnace:
    description: This is a command for cooking items.
  furnaces:
    description: This is a command for settings.
    permission: furnace.settings

